[package]
name = "mask_parser"
version = "0.1.0"
authors = ["Jake Deichert <git@jakedeichert.com>"]
edition = "2018"
license = "MIT"
publish = false

[dependencies]
pulldown-cmark = { version = "0.5", default-features = false }          # https://github.com/raphlinus/pulldown-cmark
